
lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem' # путь к приватному ключу
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'  # путь к публичному ключу
    pass_phrase:      'root'                             # пароль от приватного ключа
    token_ttl:        3600
    user_identity_field: email