version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql  # или используйте другую нужную вам версию MySQL
    environment:
      MYSQL_DATABASE: 'taskManager'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'testPass'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql


      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  db_data:

  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
